language: go
go:
  - master # This uses automatically the latest version of go
# Specify which branches to build using a safelist
# branches:
#   only:
#     - master 
install:
  # 安装最新的hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  # 安装主题
  - git clone https://github.com/rhazdon/hugo-theme-hello-friend-ng.git themes/hello-friend-ng


script:
  # 运行hugo命令
  - hugo
after_script:
  # 部署
  - cd ./public
  - git init
  - git config user.name "ZhangJin233" 
  - git config user.email "jane.zhangjin@outlook.com" 
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master
  # Github Pages
  - git push --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags


env:
 global:
   # Github Pages
   - GH_REF="github.com/ZhangJin233/ZhangJin233.github.io"

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: ZhangJin233/ZhangJin233.github.io 
  provider: pages
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: jane.zhangjin@outlook.com 
  name: "ZhangJin233"
  fqdn: https://jane-dev.com # 如果是自定义域名，此处要填
  keep-history: true # 是否保持target-branch分支的提交记录
  on:
    branch: master