baseURL = "https://jane-dev.com"
languageCode = "zh-cn"
title = "jane's blog"
paginate = "10"   
theme = "hello-friend-ng"
hasCJKLanguage = true
# Google Analytics UA number
googleAnalytics = "UA-141032533-1"

DefaultContentLanguage = "zh"

PygmentsCodeFences = true
PygmentsStyle = "monokai"


disqusShortname = "https-jane-dev-com"


archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[outputs]
home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "jane's blog"

# [permalinks]
#   posts = "/posts/:year/:month/:title/"

[author]
  name = "Jane"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

  # Metadata mostly used in document's head
  description = "hello"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  homeSubtitle = "hello"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "content/posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#252627"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  # Social icons

  [[params.social]]
    name = "email"
    url  = "mailto:jane.zhangjin@outlook.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ZhangJin233/"



  [params.theme]
    subtitle = "happy every day"
    post_type = "page" # For archive
    archive_post_type = "home"
    readmore = true 

[languages]
  [languages.en]
    subtitle  = "Hello Friend NG Theme"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.zh]
    subtitle  = "Hello Friend NG Theme"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  # [[menu.main]]
  #   identifier = "blog"
  #   name       = "Blog"
  #   url        = "posts/"
  [[menu.main]]
    identifier = "tech"
    name       = "Technology"
    url        = "technology/"
  [[menu.main]]
    identifier = "reading"
    name       = "Reading"
    url        = "reading/"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

